import { useState } from "react";
import { Sparkles } from "lucide-react";
import { cn } from "@/lib/utils";

/**
 * The model that powers every AI feature in Membr. Update this in one place
 * when the model changes so all disclosures stay in sync.
 */
export const AI_MODEL_LABEL = "Claude Haiku 4.5";
export const AI_PROVIDER_LABEL = "Anthropic";

interface AIBadgeProps {
  /** Short context for the badge (e.g. "search results", "photo description"). */
  feature?: string;
  /** Visual variant — "inline" sits next to text; "footer" anchors below content. */
  variant?: "inline" | "footer";
  className?: string;
}

/**
 * Subtle disclosure shown wherever Membr surfaces AI-generated content.
 * Tap to reveal which model produced the output. Required for App Store
 * Review Guideline 2.5.18 (generative AI labeling).
 */
export function AIBadge({ feature, variant = "inline", className }: AIBadgeProps) {
  const [open, setOpen] = useState(false);
  return (
    <div className={cn("relative inline-flex items-center", className)}>
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        onBlur={() => setOpen(false)}
        className={cn(
          "inline-flex items-center gap-1 rounded-sm text-[11px] font-medium text-muted-text",
          "hover:text-foreground transition-colors",
          variant === "footer" && "mt-2",
        )}
        aria-label={`AI disclosure${feature ? ` for ${feature}` : ""}`}
      >
        <Sparkles className="w-3 h-3" strokeWidth={1.75} />
        <span>AI generated</span>
      </button>
      {open && (
        <div
          role="tooltip"
          /* Anchor right so the popover grows leftward into the card
             instead of off the screen edge. The badge typically sits in
             a right-aligned slot; left-anchoring caused horizontal
             scroll on narrow viewports. */
          className="absolute z-10 right-0 top-full mt-1 w-56 max-w-[calc(100vw-2.5rem)] rounded-md bg-surface-2 border border-[hsl(0_0%_100%/0.12)] px-3 py-2 text-[11px] text-foreground shadow-xl"
        >
          {feature ? `This ${feature} was generated by ` : "Generated by "}
          <span className="font-semibold">{AI_MODEL_LABEL}</span>
          <span className="text-muted-text"> ({AI_PROVIDER_LABEL})</span>
          <span className="block mt-1 text-muted-text">
            Membr does not train this model on your data.
          </span>
        </div>
      )}
    </div>
  );
}
